#pragma once
#define CFG_TUSB_MCU OPT_MCU_NONE
#define CFG_TUSB_OS OPT_OS_NONE
#define CFG_TUD_ENABLED 1
#define CFG_TUD_NCM 1
#define CFG_TUD_ENDPOINT0_SIZE 64
#define TUP_DCD_ENDPOINT_MAX 8
#define CFG_TUD_NCM_IN_NTB_N 6
#define CFG_TUD_NCM_OUT_NTB_N 6
#define CFG_TUD_NCM_IN_NTB_MAX_SIZE 8192
#define CFG_TUD_NCM_OUT_NTB_MAX_SIZE 8192
#define CFG_TUD_NCM_IN_MAX_DATAGRAMS_PER_NTB 6
