static const char MESHVPN_WEB_INDEX_HTML[] =
"<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>MeshVPN Device</title>"
"<style>"
"body{font-family:system-ui,sans-serif;margin:0;padding:16px;background:#0f1115;color:#e8eaed}"
"h1{font-size:1.25rem}section{background:#1a1d24;border-radius:8px;padding:12px;margin:12px 0}"
"label{display:block;margin:8px 0 4px}input,select,button{width:100%;padding:8px;border-radius:6px;border:1px solid #333;background:#111;color:#eee;box-sizing:border-box}"
"button{margin-top:8px;cursor:pointer;background:#2b59ff;border-color:#2b59ff}"
".row{display:flex;gap:8px}.row button{flex:1}.ok{color:#6ee7a8}.err{color:#f87171}.warn{color:#fbbf24}pre{white-space:pre-wrap;font-size:12px}"
"#wifistate,#usbstate{font-weight:600;margin:4px 0 8px}"
"</style></head><body>"
"<h1>MeshVPN Dongle</h1>"
"<section><h2>Status</h2><div id='usbstate'>...</div>"
"<pre id='status'>Loading...</pre><button onclick='loadStatus()'>Refresh</button></section>"
"<section><h2>Logs</h2><button onclick='loadLogs()'>Load device log</button><pre id='logs'></pre></section>"
"<section><h2>WiFi</h2>"
"<div id='wifistate'>...</div>"
"<button onclick='scanWifi()'>Scan networks</button>"
"<select id='ssid'></select>"
"<label>Password<input id='pass' type='password'></label>"
"<button onclick='saveWifi()'>Connect &amp; save</button></section>"
"<section><h2>Admin</h2>"
"<label>New password<input id='admin' type='password'></label>"
"<button onclick='saveAdmin()'>Change password</button>"
"<button onclick='reboot()'>Reboot</button>"
"<button onclick='factoryReset()' style='background:#b91c1c;border-color:#b91c1c'>Factory reset</button></section>"
"<section><h2>VPN</h2>"
"<label>Protocol<select id='vpn_transport' onchange='vpnUiToggle()'>"
"<option value='tls'>tls</option><option value='transparent-tls'>transparent-tls</option>"
"<option value='boring-tls'>boring-tls</option></select></label>"
"<label>Server<input id='vpn_server' placeholder='host:443'></label>"
"<div id='vpn_tls_fields'>"
"<label>TLS server name<input id='vpn_sni' placeholder='clean-vpn'></label>"
"<label>HTTP version<select id='vpn_http'><option value='2'>HTTP/2</option><option value='1'>HTTP/1.1</option></select></label>"
"</div>"
"<div id='vpn_transparent_fields' style='display:none'>"
"<label>TLS public name (enc-SNI)<input id='vpn_pubname' placeholder='relay.example.com'></label>"
"<p class='warn'>Exit must run --type=transparent-tls with same --tls-public-name</p>"
"</div>"
"<div id='vpn_boring_fields' style='display:none'>"
"<label>ClientHello profile<select id='vpn_profile'></select></label>"
"<label><input id='vpn_ja3_strict' type='checkbox'> JA3 strict</label>"
"<label>Upload profile JSON<input id='vpn_profile_file' type='file' accept='.json'></label>"
"<button type='button' onclick='uploadProfile()'>Upload profile</button>"
"</div>"
"<label><input id='vpn_en' type='checkbox'> Enable VPN</label>"
"<label>CA certificate (PEM)<input id='vpn_ca_file' type='file' accept='.pem'></label>"
"<button type='button' onclick='uploadCa()'>Upload CA</button>"
"<label>HMAC key<input id='vpn_psk_file' type='file'></label>"
"<button type='button' onclick='uploadPsk()'>Upload PSK</button>"
"<button onclick='saveVpn()'>Save VPN config</button></section>"
"<section><h2>Routing</h2>"
"<label>Default action<select id='rt_default'><option value='direct'>direct</option><option value='vpn'>vpn</option><option value='block'>block</option></select></label>"
"<label>IP/CIDR rule<input id='rt_match' placeholder='10.0.0.0/8'></label>"
"<label>Action<select id='rt_action'><option value='vpn'>vpn</option><option value='direct'>direct</option><option value='block'>block</option></select></label>"
"<button onclick='addRule()'>Add rule</button><pre id='rules'></pre></section>"
"<p id='msg'></p>"
"<script>"
"const auth=sessionStorage.getItem('auth')||'';"
"async function api(path,opts={}){"
"opts.headers=opts.headers||{};opts.headers['Authorization']='Bearer '+auth;"
"if(opts.body&&typeof opts.body!=='string'){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(opts.body);}"
"const r=await fetch(path,opts);if(r.status===401){location.href='/login';throw new Error('auth');}"
"return r.json();}"
"function setMsg(t,ok){const m=document.getElementById('msg');m.textContent=t;m.className=ok?'ok':'err';}"
"const REASONS={2:'auth expired',15:'wrong password',201:'network not found',202:'auth failed',203:'assoc failed',205:'connection failed'};"
"function renderWifi(w){const e=document.getElementById('wifistate');if(!w){e.textContent='unknown';return;}"
"if(w.connected){e.textContent='Connected to '+w.ssid+' \\u2014 '+w.ip+' ('+w.rssi+' dBm)';e.className='ok';return true;}"
"const why=w.disconnect_reason?(REASONS[w.disconnect_reason]||('reason '+w.disconnect_reason)):'';"
"if(w.configured&&w.ssid){e.textContent='Connecting to '+w.ssid+'...'+(why?' last error: '+why:'');e.className=why?'err':'warn';}"
"else if(w.configured){e.textContent='Saved WiFi \\u2014 reconnecting after boot...';e.className='warn';}"
"else{e.textContent='No network configured \\u2014 pick one below';e.className='warn';}return false;}"
"function renderUsb(u,net){const e=document.getElementById('usbstate');if(!u){e.textContent='';return;}"
"if(!u.host_ready){e.textContent='USB: no host attached ('+u.profile+')';e.className='warn';return;}"
"e.textContent='USB '+u.profile+' host attached \\u2014 http://'+net.usb_ip+'/ \\u2014 sent '+u.tx_ok"
"+(net.usb_napt?' NAT on':' NAT OFF')"
"+(u.tx_dropped?', dropped '+u.tx_dropped:'')+(u.tx_retried?', retried '+u.tx_retried:'');"
"e.className=(!net.usb_napt||u.tx_dropped>u.tx_ok)?'err':'ok';}"
"async function loadStatus(){const j=await api('/api/status');document.getElementById('status').textContent=JSON.stringify(j,null,2);"
"renderWifi(j.wifi);renderUsb(j.usb,j.net);document.getElementById('rt_default').value=j.routing&&j.routing.default||'direct';loadRules();}"
"async function watchWifi(){for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,2000));"
"const j=await api('/api/status');document.getElementById('status').textContent=JSON.stringify(j,null,2);"
"if(renderWifi(j.wifi)){setMsg('WiFi connected: '+j.wifi.ip,true);return;}}"
"setMsg('Still not connected \\u2014 check the log',false);}"
"async function loadLogs(){const r=await fetch('/api/logs',{headers:{'Authorization':'Bearer '+auth}});"
"if(r.status===401){location.href='/login';return;}const t=await r.text();const e=document.getElementById('logs');e.textContent=t;e.scrollTop=e.scrollHeight;}"
"async function scanWifi(){setMsg('Scanning...',true);const j=await api('/api/wifi/scan');const s=document.getElementById('ssid');s.innerHTML='';"
"j.networks.forEach(n=>{const o=document.createElement('option');o.value=n.ssid;o.textContent=n.ssid+' ('+n.rssi+' dBm)';s.appendChild(o);});setMsg('Found '+j.networks.length+' networks',true);}"
"async function saveWifi(){await api('/api/wifi/connect',{method:'POST',body:{ssid:document.getElementById('ssid').value,password:document.getElementById('pass').value}});"
"setMsg('WiFi saved, connecting...',true);watchWifi();}"
"async function saveAdmin(){await api('/api/admin/password',{method:'POST',body:{password:document.getElementById('admin').value}});setMsg('Password updated',true);}"
"async function reboot(){await api('/api/system/reboot',{method:'POST'});setMsg('Rebooting...',true);}"
"async function factoryReset(){if(!confirm('Erase all settings?'))return;await api('/api/system/factory-reset',{method:'POST'});setMsg('Reset, rebooting...',true);}"
"async function saveVpn(){const r=await api('/api/vpn/config',{method:'POST',body:{"
"transport:document.getElementById('vpn_transport').value,"
"server:document.getElementById('vpn_server').value,"
"sni:document.getElementById('vpn_sni').value,"
"tls_public_name:document.getElementById('vpn_pubname').value,"
"http_vers:parseInt(document.getElementById('vpn_http').value,10),"
"profile_name:document.getElementById('vpn_profile').value,"
"ja3_strict:document.getElementById('vpn_ja3_strict').checked,"
"enabled:document.getElementById('vpn_en').checked}});"
"if(!r.ok){setMsg('VPN save failed: '+(r.error||'?'),false);return;}"
"setMsg('VPN config saved',true);loadStatus();loadVpn();}"
"function vpnUiToggle(){const t=document.getElementById('vpn_transport').value;"
"document.getElementById('vpn_tls_fields').style.display=(t==='transparent-tls')?'none':'block';"
"document.getElementById('vpn_transparent_fields').style.display=(t==='transparent-tls')?'block':'none';"
"document.getElementById('vpn_boring_fields').style.display=(t==='boring-tls')?'block':'none';}"
"async function loadVpn(){const j=await api('/api/vpn/config');"
"document.getElementById('vpn_transport').value=j.transport||'tls';"
"document.getElementById('vpn_server').value=j.server||'';"
"document.getElementById('vpn_sni').value=j.tls_server_name||'';"
"document.getElementById('vpn_pubname').value=j.tls_public_name||'';"
"document.getElementById('vpn_http').value=String(j.http_vers||2);"
"document.getElementById('vpn_en').checked=!!j.enabled;"
"document.getElementById('vpn_ja3_strict').checked=!!j.ja3_strict;"
"vpnUiToggle();const ps=await api('/api/vpn/profiles');const sel=document.getElementById('vpn_profile');sel.innerHTML='';"
"(ps.profiles||[]).forEach(p=>{const o=document.createElement('option');o.value=p;o.textContent=p;sel.appendChild(o);});"
"if(j.profile_name)sel.value=j.profile_name;}"
"async function uploadFile(path,file){const fd=new FormData();fd.append('file',file);"
"const r=await fetch(path,{method:'POST',headers:{'Authorization':'Bearer '+auth},body:fd});"
"if(r.status===401){location.href='/login';return;}if(!r.ok)throw new Error('upload failed');return r.json();}"
"async function uploadCa(){const f=document.getElementById('vpn_ca_file').files[0];if(!f)return;"
"await uploadFile('/api/vpn/certs/ca',f);setMsg('CA uploaded',true);}"
"async function uploadPsk(){const f=document.getElementById('vpn_psk_file').files[0];if(!f)return;"
"await uploadFile('/api/vpn/certs/psk',f);setMsg('PSK uploaded',true);}"
"async function uploadProfile(){const f=document.getElementById('vpn_profile_file').files[0];if(!f)return;"
"await uploadFile('/api/vpn/profiles',f);setMsg('Profile uploaded',true);loadVpn();}"
"async function loadRules(){const j=await api('/api/routing/rules');document.getElementById('rules').textContent=JSON.stringify(j.rules,null,2);}"
"async function addRule(){await api('/api/routing/rules',{method:'POST',body:{type:'ip_cidr',match:document.getElementById('rt_match').value,action:document.getElementById('rt_action').value,enabled:true}});"
"await api('/api/routing/default',{method:'POST',body:{action:document.getElementById('rt_default').value}});loadRules();setMsg('Rule added',true);}"
"loadStatus();loadVpn();"
"</script></body></html>";

static const char MESHVPN_WEB_LOGIN_HTML[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>MeshVPN Login</title><style>body{font-family:system-ui;background:#0f1115;color:#eee;display:flex;min-height:100vh;align-items:center;justify-content:center}"
"form{background:#1a1d24;padding:24px;border-radius:8px;width:320px}input,button{width:100%;padding:10px;margin:8px 0;box-sizing:border-box;border-radius:6px;border:1px solid #333;background:#111;color:#eee}"
"button{background:#2b59ff;border-color:#2b59ff;cursor:pointer}</style></head><body>"
"<form onsubmit='login(event)'><h2>MeshVPN</h2><input id='p' type='password' placeholder='Admin password' required>"
"<button type='submit'>Login</button><p id='e'></p></form>"
"<script>async function login(e){e.preventDefault();const p=document.getElementById('p').value;"
"const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:p})});"
"if(!r.ok){document.getElementById('e').textContent='Invalid password';return;}"
"const j=await r.json();sessionStorage.setItem('auth',j.token);location.href='/';}</script></body></html>";
