#pragma once

static const char MESHVPN_WEB_INDEX_HTML[] =
"<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>MeshPN</title><style>\n"
":root{color-scheme:dark}body{font:16px system-ui;max-width:900px;margin:auto;padding:20px;background:#10141b;color:#edf2f7}\n"
"section{padding:18px;margin:16px 0;border:1px solid #334155;border-radius:12px;background:#18212d}h1{margin-bottom:4px}h2{font-size:1.2rem}\n"
"label{display:block;margin:12px 0 4px}input,select,button,textarea{font:inherit;padding:9px;border-radius:6px;border:1px solid #64748b;background:#111827;color:inherit;max-width:100%;box-sizing:border-box}\n"
"input:not([type=checkbox]),select,textarea{width:100%}button{cursor:pointer;margin:6px 5px 0 0;background:#23467b}button:disabled{opacity:.5;cursor:default}\n"
"pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;max-height:450px;overflow:auto}small,.muted{color:#b2c0d3}.row{display:flex;gap:18px;flex-wrap:wrap}.metric{min-width:150px}.metric strong{display:block;font-size:24px}#message{position:sticky;top:0;background:#18212d;padding:10px;z-index:1;white-space:pre-wrap}.error{color:#ffa8a8}.success{color:#a5efc0}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:8px;border-bottom:1px solid #334155}.scroll{overflow:auto}\n"
"</style></head><body><h1>MeshPN</h1><small>USB WiFi dongle · <a href=\"//meshpn.local/\">meshpn.local</a></small><p id=\"message\" role=\"status\" hidden></p>\n"
"<section><h2>Status</h2><div class=\"row\"><div class=\"metric\">Chip temperature<strong id=\"temperature\">—</strong></div><div class=\"metric\">Internal RAM free<strong id=\"ram\">—</strong></div><div class=\"metric\">PSRAM free<strong id=\"psram\">—</strong></div></div><p id=\"connection\">Loading…</p><p id=\"cpu\"></p><p id=\"usb\"></p><p id=\"ap\"></p><details><summary>Diagnostics</summary><pre id=\"status\"></pre></details><small>Updates every 2 seconds while this page is visible.</small></section>\n"
"<section id=\"admin\"><h2>Admin</h2><p id=\"password-warning\" hidden>Set a new admin password before configuring the device.</p>\n"
"<form id=\"password-form\"><label>New admin password (8–64 bytes)<input id=\"admin-password\" type=\"password\" minlength=\"8\" maxlength=\"64\" autocomplete=\"new-password\" required></label><button>Change password</button><button type=\"button\" id=\"logout\">Log out</button></form></section>\n"
"<section><h2>WiFi networks</h2><p>Only 2.4 GHz. Higher priority is tried first; a working connection stays active.</p><div class=\"scroll\"><table><thead><tr><th>Network</th><th>Priority</th><th>Enabled</th><th>Actions</th></tr></thead><tbody id=\"profiles\"></tbody></table></div>\n"
"<button id=\"scan\">Scan networks</button><button id=\"auto\">Resume automatic selection</button><button id=\"pause\">Disconnect / pause</button>\n"
"<label>Nearby networks<select id=\"nearby\"><option value=\"\">Scan or enter an SSID below</option></select></label>\n"
"<form id=\"wifi-form\"><h3 id=\"editor-title\">Add network</h3><label>SSID<input id=\"ssid\" maxlength=\"32\" required autocomplete=\"off\"></label>\n"
"<label>Security<select id=\"security\"><option value=\"1\">WPA2 / WPA2-WPA3 Personal</option><option value=\"2\">WPA3 Personal</option><option value=\"0\">Open network</option></select></label>\n"
"<label>Password<input id=\"wifi-password\" type=\"password\" maxlength=\"63\" autocomplete=\"new-password\" placeholder=\"Leave blank when editing to keep saved password\"></label>\n"
"<label>Priority<input id=\"priority\" type=\"number\" min=\"-1000\" max=\"1000\" value=\"0\" required></label>\n"
"<label><input id=\"enabled\" type=\"checkbox\" checked> Enabled</label><label><input id=\"hidden-network\" type=\"checkbox\"> Hidden SSID</label>\n"
"<button type=\"submit\">Save</button><button type=\"button\" id=\"save-connect\">Save and connect</button><button type=\"button\" id=\"new-profile\">New profile</button></form></section>\n"
"<section><h2>IP-list memory benchmark</h2><p>Synthetic lookup test in PSRAM. Routing is not enabled.</p><select id='range-count'><option>10000</option><option selected>100000</option><option>500000</option></select><button id='benchmark'>Run benchmark</button><pre id='benchmark-result'></pre></section><section><h2>Logs</h2><button id=\"load-logs\">Load device log</button><pre id=\"logs\"></pre></section>\n"
"<section><h2>Admin connection</h2><label><input id=\"https-enabled\" type=\"checkbox\" disabled> Enable HTTPS</label><button id=\"save-https\" disabled>Save connection setting</button><p id=\"https-mode\"></p><p>HTTPS uses a device certificate; the first visit may show a trust warning. HTTP sends passwords and tokens without encryption. Changes apply after reboot.</p><div id=\"https-pending\" hidden><p>After reboot, open <a id=\"https-next-url\" rel=\"noreferrer\"></a> and log in again.</p><button id=\"apply-https\">Reboot to apply</button></div></section>\n"
"<section id=\"certificate-section\" hidden><h2>HTTPS certificate</h2><p>The first certificate is unique to this device and self-signed. Verify its fingerprint on a trusted USB connection. You can import a certificate issued by your own trusted CA.</p><label>Current SHA-256 fingerprint</label><pre id=\"fingerprint\"></pre><button id=\"download-cert\">Download device certificate</button>\n"
"<details><summary>Import certificate and private key</summary><p>The certificate must include meshpn.local. The new identity takes effect after reboot.</p><label>Certificate PEM<input id=\"cert-file\" type=\"file\" accept=\".pem,.crt\"></label><label>Private key PEM<input id=\"key-file\" type=\"file\" accept=\".pem,.key\"></label><button id=\"import-cert\">Import</button></details></section>\n"
"<section><h2>System</h2><button id=\"reboot\">Reboot</button><button id=\"reset\">Factory reset</button><p class=\"muted\">VPN and policy routing are not implemented yet. All internet traffic currently uses WiFi directly.</p></section>\n"
"<script>\n"
"const $=id=>document.getElementById(id);let auth=sessionStorage.getItem('auth')||'',profiles=[],editing=null,statusTimer=null,stopped=false,statusBusy=false,httpsDirty=false,httpsSaving=false,httpsSaved=false;\n"
"if(!auth)location.replace('/login');\n"
"function message(text,bad=false){$('message').hidden=false;$('message').textContent=text;$('message').className=bad?'error':'success';}\n"
"async function api(path,method='GET',data,raw=false){\n"
" const r=await fetch(path,{method,headers:{Authorization:'Bearer '+auth,...(data===undefined?{}:{'Content-Type':'application/json'})},body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(12000)});\n"
" if(r.status===401){stopped=true;sessionStorage.removeItem('auth');location.replace('/login');throw Error('Session expired');}\n"
" if(!r.ok)throw Error(await r.text());return raw?r:r.json();\n"
"}\n"
"function run(fn){return async event=>{event?.preventDefault();try{await fn(event);}catch(e){message(e.message,true);}};}\n"
"function size(n){return (n/1024).toFixed(0)+' KiB';}\n"
"function renderHttps(s){\n"
" httpsSaved=s.https_configured;\n"
" if(!httpsDirty&&!httpsSaving)$('https-enabled').checked=httpsSaved;\n"
" $('https-enabled').disabled=httpsSaving;$('save-https').disabled=httpsSaving;\n"
" $('https-mode').textContent='Active: '+(s.https_enabled?'HTTPS':'HTTP')+(s.https_restart_required?' · Saved change requires reboot.':'');\n"
" $('https-pending').hidden=!s.https_restart_required;$('apply-https').disabled=httpsSaving;\n"
" $('https-next-url').href=s.admin_next_url;$('https-next-url').textContent=s.admin_next_url;\n"
"}\n"
"async function poll(){\n"
" clearTimeout(statusTimer);if(stopped||document.hidden||statusBusy)return;statusBusy=true;\n"
" try{const s=await api('/api/status');renderHttps(s);$('temperature').textContent=s.temperature_c==null?'Unavailable':s.temperature_c.toFixed(1)+' °C';\n"
" $('ram').textContent=size(s.memory.internal.free);$('psram').textContent=size(s.memory.psram.free);$('status').textContent=JSON.stringify(s,null,2);\n"
" $('cpu').textContent=s.cpu?.cores?.map(c=>'CPU'+c.id+' '+(s.cpu.available!==false&&Number.isFinite(c.load_pct)?c.load_pct.toFixed(1)+'%':'—')).join(' · ')||'CPU telemetry unavailable';\n"
" $('certificate-section').hidden=!s.https_enabled;$('fingerprint').textContent=s.certificate_sha256||'';$('password-warning').hidden=!s.must_change_password;\n"
" $('connection').textContent=s.wifi.connected?'Connected: '+s.wifi.ssid+' · '+s.wifi.ip+' · '+s.wifi.rssi+' dBm':'WiFi: '+s.wifi.state+(s.wifi.ssid?' · '+s.wifi.ssid:'')+(s.wifi.disconnect_reason?' · reason '+s.wifi.disconnect_reason:'');\n"
" $('usb').textContent='USB '+s.usb.profile+' · '+(s.usb.host_ready?'host connected':'no host')+' · '+(s.https_enabled?'https://':'http://')+s.net.usb_ip+'/';\n"
" $('ap').textContent=s.net.ap_active?'AP: '+s.net.ap_ssid+' · '+s.net.ap_ip+' · channel '+s.net.ap_channel+' · clients '+s.net.ap_clients+' · NAT '+(s.net.ap_napt?'on':'off')+' · admin: '+(s.https_enabled?'https':'http')+'://'+s.net.ap_ip+'/':'WiFi AP disabled';\n"
" }catch(e){message('Status unavailable: '+e.message,true);}finally{statusBusy=false;if(!stopped&&!document.hidden)statusTimer=setTimeout(poll,2000);}\n"
"}\n"
"document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(statusTimer);else poll();});\n"
"function button(text,fn){const b=document.createElement('button');b.textContent=text;b.onclick=run(fn);return b;}\n"
"async function loadProfiles(){\n"
" profiles=(await api('/api/wifi/profiles')).profiles;$('profiles').replaceChildren();\n"
" for(const p of profiles){const tr=document.createElement('tr');for(const value of [p.ssid,p.priority,p.enabled?'Yes':'No']){const td=document.createElement('td');td.textContent=value;tr.append(td);}\n"
" const actions=document.createElement('td');actions.append(button('Edit',()=>edit(p)),button('Connect',()=>api('/api/wifi/select','POST',{id:p.id})),button('Delete',async()=>{if(confirm('Delete '+p.ssid+'?')){await api('/api/wifi/profiles','POST',{id:p.id,delete:true});if(editing===p.id)edit(null);await loadProfiles();}}));tr.append(actions);$('profiles').append(tr);}\n"
"}\n"
"function edit(p){editing=p?.id??null;$('editor-title').textContent=p?'Edit network':'Add network';$('ssid').value=p?.ssid?? '';$('security').value=p?.security??1;$('wifi-password').value='';$('priority').value=p?.priority??0;$('enabled').checked=p?.enabled??true;$('hidden-network').checked=p?.hidden??false;}\n"
"async function save(connect=false){\n"
" if(!$('wifi-form').reportValidity())return;\n"
" const p={ssid:$('ssid').value,security:Number($('security').value),priority:Number($('priority').value),enabled:$('enabled').checked,hidden:$('hidden-network').checked,connect};\n"
" if(editing!==null)p.id=editing;\n"
" if($('wifi-password').value||editing===null)p.password=$('wifi-password').value;\n"
" await api('/api/wifi/profiles','POST',p);$('wifi-password').value='';edit(null);await loadProfiles();message(connect?'Saved. Connecting…':'Network saved.');\n"
"}\n"
"$('wifi-form').onsubmit=run(()=>save(false));$('save-connect').onclick=run(()=>save(true));$('new-profile').onclick=()=>edit(null);\n"
"$('auto').onclick=run(()=>api('/api/wifi/select','POST',{id:0}));$('pause').onclick=run(()=>api('/api/wifi/select','POST',{pause:true}));\n"
"async function scanNetworks(initial=false){\n"
" $('scan').disabled=true;\n"
" try{\n"
"  if(!initial||!(await api('/api/wifi/scan')).scanning)await api('/api/wifi/scan','POST',{});\n"
"  for(let attempt=0;attempt<20;attempt++){\n"
"   await new Promise(resolve=>setTimeout(resolve,1000));\n"
"   const s=await api('/api/wifi/scan');if(s.scanning)continue;\n"
"   $('nearby').replaceChildren(new Option('Choose a network',''));\n"
"   for(const n of s.networks){if(!n.ssid)continue;const o=new Option(n.ssid+' ('+n.rssi+' dBm)',n.ssid);o.dataset.security=n.authmode===0?'0':n.authmode===6?'2':'1';$('nearby').append(o);}\n"
"   message('Scan complete.');return;\n"
"  }\n"
"  throw Error('Scan timed out; retry after WiFi finishes connecting.');\n"
" }finally{$('scan').disabled=false;}\n"
"}\n"
"$('scan').onclick=run(()=>scanNetworks());\n"
"$('nearby').onchange=()=>{const o=$('nearby').selectedOptions[0];if(o.value){edit(profiles.find(p=>p.ssid===o.value)||null);$('ssid').value=o.value;$('security').value=o.dataset.security;}};\n"
"$('https-enabled').onchange=()=>{httpsDirty=true;};\n"
"$('save-https').onclick=run(async()=>{\n"
" const enabled=$('https-enabled').checked;\n"
" if(enabled!==httpsSaved&&!confirm(enabled?'Enable HTTPS after reboot? The browser may ask you to trust the device certificate.':'Disable HTTPS after reboot? Passwords and tokens will travel without encryption.'))return;\n"
" httpsSaving=true;$('save-https').disabled=true;$('https-enabled').disabled=true;\n"
" try{const s=await api('/api/admin/https','POST',{enabled});httpsDirty=false;httpsSaving=false;renderHttps(s);message(s.https_restart_required?'Saved. Reboot to apply; use the new address shown below.':'Saved. No reboot needed.');}\n"
" finally{httpsSaving=false;$('save-https').disabled=false;$('https-enabled').disabled=false;}\n"
"});\n"
"$('apply-https').onclick=run(async()=>{\n"
" if(!confirm('Reboot now to apply the saved connection setting?'))return;\n"
" await api('/api/system/reboot','POST',{});stopped=true;clearTimeout(statusTimer);sessionStorage.removeItem('auth');$('apply-https').disabled=true;\n"
" message('Rebooting. Open the address shown in Admin connection and log in again.');\n"
"});\n"
"$('password-form').onsubmit=run(async()=>{await api('/api/admin/password','POST',{password:$('admin-password').value});sessionStorage.removeItem('auth');location.replace('/login');});\n"
"$('logout').onclick=run(async()=>{await api('/api/logout','POST',{});sessionStorage.removeItem('auth');location.replace('/login');});\n"
"$('load-logs').onclick=run(async()=>{$('logs').textContent=await (await api('/api/logs','GET',undefined,true)).text();});\n"
"$('download-cert').onclick=run(async()=>{const r=await api('/api/certificate','GET',undefined,true);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='meshpn-device.pem';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});\n"
"$('import-cert').onclick=run(async()=>{const crt=$('cert-file').files[0],key=$('key-file').files[0];if(!crt||!key||crt.size>4095||key.size>2047)throw Error('Choose certificate and key PEM files within 4095 / 2047 bytes');\n"
" await api('/api/certificate','POST',{certificate:await crt.text(),private_key:await key.text()});$('key-file').value='';message('Certificate saved. Reboot to apply.');});\n"
"$('reboot').onclick=run(async()=>{await api('/api/system/reboot','POST',{});message('Rebooting…');});\n"
"$('reset').onclick=run(async()=>{if(confirm('Erase all settings and the HTTPS identity?')){await api('/api/system/factory-reset','POST',{});sessionStorage.removeItem('auth');message(location.protocol==='https:'?'Resetting. The new certificate will need verification.':'Resetting settings…');}});\n"
"$('benchmark').onclick=run(async()=>{$('benchmark-result').textContent=JSON.stringify(await api('/api/routing/benchmark','POST',{count:Number($('range-count').value)}),null,2);});\n"
"poll();run(async()=>{await loadProfiles();await scanNetworks(true);})();\n"
"</script></body></html>\n"
"\n";

static const char MESHVPN_WEB_LOGIN_HTML[] =
"<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>MeshPN Login</title><style>:root{color-scheme:dark}body{font:16px system-ui;background:#10141b;color:#edf2f7;max-width:360px;margin:15vh auto;padding:20px}input,button{font:inherit;box-sizing:border-box;width:100%;padding:12px;margin:10px 0}#error{color:#ffa8a8}</style></head><body><h1>MeshPN</h1><p>Admin access over USB or device WiFi AP</p><form id=\"login\"><label>Password<input id=\"password\" type=\"password\" autocomplete=\"current-password\" required></label><button>Log in</button></form><p id=\"error\"></p><script>document.getElementById('login').onsubmit=async e=>{e.preventDefault();try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.getElementById('password').value}),signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(await r.text());const j=await r.json();sessionStorage.setItem('auth',j.token);location.replace('/');}catch(e){document.getElementById('error').textContent=e.message;}};</script></body></html>\n";
