# Replace one source in TinyUSB's target with a generated build copy.
# No dependency checkout modifications and no instrumentation for ECM/RNDIS.
if(CONFIG_MESHVPN_NCM_TELEMETRY)
    idf_component_get_property(ncm_tusb_lib espressif__tinyusb COMPONENT_LIB)
    idf_component_get_property(ncm_tusb_dir espressif__tinyusb COMPONENT_DIR)
    idf_build_get_property(ncm_python PYTHON)
    set(ncm_original "${ncm_tusb_dir}/src/class/net/ncm_device.c")
    set(ncm_generator "${CMAKE_SOURCE_DIR}/scripts/instrument-ncm.py")
    set(ncm_generated "${CMAKE_BINARY_DIR}/meshpn-generated/ncm_device.c")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ncm_original}" "${ncm_generator}")
    execute_process(COMMAND "${ncm_python}" "${ncm_generator}" "${ncm_original}" "${ncm_generated}"
        RESULT_VARIABLE ncm_result ERROR_VARIABLE ncm_error)
    if(NOT ncm_result EQUAL 0)
        message(FATAL_ERROR "NCM instrumentation failed: ${ncm_error}")
    endif()
    get_target_property(ncm_sources ${ncm_tusb_lib} SOURCES)
    set(ncm_matches 0)
    set(ncm_replaced "")
    foreach(ncm_source IN LISTS ncm_sources)
        if(ncm_source MATCHES "(^|/)src/class/net/ncm_device\\.c$")
            list(APPEND ncm_replaced "${ncm_generated}")
            math(EXPR ncm_matches "${ncm_matches}+1")
        else()
            list(APPEND ncm_replaced "${ncm_source}")
        endif()
    endforeach()
    if(NOT ncm_matches EQUAL 1)
        message(FATAL_ERROR "Expected one TinyUSB NCM source, found ${ncm_matches}")
    endif()
    set_property(TARGET ${ncm_tusb_lib} PROPERTY SOURCES "${ncm_replaced}")
    target_include_directories(${ncm_tusb_lib} PRIVATE
        "${ncm_tusb_dir}/src/class/net" "${CMAKE_SOURCE_DIR}/components/meshvpn_usb/include")
    # TinyUSB is linked after the application components. Pull the observer
    # from meshvpn_usb even if no web consumer references its object yet.
    target_link_options(${ncm_tusb_lib} INTERFACE "LINKER:--undefined=meshvpn_ncm_record")
    message(STATUS "MeshPN: passive NCM telemetry enabled (pinned generated driver)")
endif()

if(CONFIG_MESHVPN_DWC2_TELEMETRY)
    set(dwc_original "${ncm_tusb_dir}/src/portable/synopsys/dwc2/dcd_dwc2.c")
    set(dwc_generator "${CMAKE_SOURCE_DIR}/scripts/instrument-dwc2.py")
    set(dwc_generated "${CMAKE_BINARY_DIR}/meshpn-generated/dcd_dwc2.c")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${dwc_original}" "${dwc_generator}")
    execute_process(COMMAND "${ncm_python}" "${dwc_generator}" "${dwc_original}" "${dwc_generated}"
        RESULT_VARIABLE dwc_result ERROR_VARIABLE dwc_error)
    if(NOT dwc_result EQUAL 0)
        message(FATAL_ERROR "DWC2 instrumentation failed: ${dwc_error}")
    endif()
    get_target_property(dwc_sources ${ncm_tusb_lib} SOURCES)
    set(dwc_matches 0)
    set(dwc_replaced "")
    foreach(dwc_source IN LISTS dwc_sources)
        if(dwc_source MATCHES "(^|/)src/portable/synopsys/dwc2/dcd_dwc2\\.c$")
            list(APPEND dwc_replaced "${dwc_generated}")
            math(EXPR dwc_matches "${dwc_matches}+1")
        else()
            list(APPEND dwc_replaced "${dwc_source}")
        endif()
    endforeach()
    if(NOT dwc_matches EQUAL 1)
        message(FATAL_ERROR "Expected one DWC2 source, found ${dwc_matches}")
    endif()
    set_property(TARGET ${ncm_tusb_lib} PROPERTY SOURCES "${dwc_replaced}")
    target_include_directories(${ncm_tusb_lib} PRIVATE "${ncm_tusb_dir}/src/portable/synopsys/dwc2")
    target_link_options(${ncm_tusb_lib} INTERFACE "LINKER:--undefined=meshvpn_dwc2_bind")
    message(STATUS "MeshPN: experimental DWC2 FIFO/ISR telemetry enabled")
endif()
